print("Prvi cjeli broj sa kojim radimo je:")
prvi = int(input())
print("Drugi cjeli broj sa kojim radimo je:")
drugi = int(input())
print("-------------------------")
print(f"Zbir    :  {prvi+drugi}")
print(f"Razlika :  {prvi-drugi}")
print(f"Proizvod:  {prvi*drugi}")
print(f"Kolicnik:  {prvi/drugi}")
